# Generated by Django 2.1.4 on 2019-02-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190207_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='其他歌手',
            name='歌手姓名',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='日本歌手',
            name='歌手姓名',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='欧美歌手',
            name='歌手姓名',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='韩国歌手',
            name='歌手姓名',
            field=models.CharField(max_length=500),
        ),
    ]
