# Generated by Django 2.1.4 on 2019-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190207_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='其他女歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='其他歌手组合',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='其他男歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='华语女歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='华语男歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='华语组合',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='日本女歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='日本男歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='日本组合',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='欧美女歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='欧美男歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='欧美组合',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='韩国女歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='韩国男歌手',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='韩国组合',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('歌手姓名', models.CharField(max_length=100)),
                ('歌手ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='其他歌手',
        ),
        migrations.DeleteModel(
            name='华语歌手',
        ),
        migrations.DeleteModel(
            name='日本歌手',
        ),
        migrations.DeleteModel(
            name='欧美歌手',
        ),
        migrations.DeleteModel(
            name='韩国歌手',
        ),
    ]
